#!/bin/bash

echo "🔐 GitHub Authentication Fix for Laurin Build"
echo "=============================================="
echo ""
echo "GitHub no longer supports password authentication."
echo "You need to use a Personal Access Token instead."
echo ""
echo "📋 Steps to fix this:"
echo ""
echo "1️⃣ Create Personal Access Token:"
echo "   • Go to: https://github.com/settings/tokens"
echo "   • Click 'Generate new token (classic)'"
echo "   • Note: 'Laurin Build - Laptop Development'"
echo "   • Expiration: 90 days or No expiration"
echo "   • Scopes: Check 'repo' and 'workflow'"
echo "   • Click 'Generate token'"
echo "   • COPY THE TOKEN (starts with ghp_)"
echo ""
echo "2️⃣ Update Git Remote URL:"
echo "   git remote set-url origin https://Bosslolo:YOUR_TOKEN@github.com/Bosslolo/laurin-build.git"
echo ""
echo "3️⃣ Test the connection:"
echo "   git push -u origin main"
echo ""
echo "🔑 When prompted for password, use your Personal Access Token"
echo "   (NOT your GitHub password)"
echo ""
echo "📚 Alternative: Use GitHub CLI (easier):"
echo "   • Install: brew install gh"
echo "   • Login: gh auth login"
echo "   • Push: git push -u origin main"
echo ""
echo "✅ After setup, you can push/pull without authentication issues!"
